package com.tradeforge.order.service;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.tradeforge.account.domain.Account;
import com.tradeforge.account.domain.AccountRepository;
import com.tradeforge.auth.web.dto.AuthResponse;
import com.tradeforge.auth.web.dto.RegisterRequest;
import com.tradeforge.common.web.CorrelationIdFilter;
import com.tradeforge.instrument.domain.Instrument;
import com.tradeforge.instrument.domain.InstrumentRepository;
import com.tradeforge.order.domain.OrderRepository;
import com.tradeforge.order.domain.OrderSide;
import com.tradeforge.order.domain.OrderType;
import com.tradeforge.order.web.dto.PlaceOrderRequest;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.MvcResult;

import java.math.BigDecimal;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.header;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

@SpringBootTest(properties = {
        "app.market-hours.enabled=false"
})
@ActiveProfiles("test")
@AutoConfigureMockMvc
public class LoggingAndTracingIT {

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private ObjectMapper objectMapper;

    @Autowired
    private InstrumentRepository instrumentRepository;

    @Autowired
    private AccountRepository accountRepository;

    @Autowired
    private OrderRepository orderRepository;

    @Autowired
    private com.tradeforge.auth.domain.UserRepository userRepository;

    private Instrument instrument;
    private AuthResponse authResponse;

    @BeforeEach
    void setUp() throws Exception {
        cleanup();

        instrument = Instrument.create("XYZ", "XYZ Corp", new BigDecimal("0.10"), new BigDecimal("10"));
        instrumentRepository.save(instrument);

        RegisterRequest registerRequest = new RegisterRequest("Trace User", "trace@tradeforge.local", "Password@1234");
        MvcResult regResult = mockMvc.perform(post("/api/v1/auth/register")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(registerRequest)))
                .andExpect(status().isCreated())
                .andReturn();

        authResponse = objectMapper.readValue(regResult.getResponse().getContentAsString(), AuthResponse.class);
        UUID userId = authResponse.userId();

        Account account = accountRepository.findByUserId(userId).orElseThrow();
        account.creditCash(new BigDecimal("10000.00"));
        accountRepository.save(account);
    }

    @AfterEach
    void tearDown() {
        cleanup();
    }

    private void cleanup() {
        orderRepository.deleteAll();
        accountRepository.deleteAll();
        userRepository.deleteAll();
        instrumentRepository.deleteAll();
    }

    @Test
    @DisplayName("Correlation ID: Provided X-Correlation-Id header is echoed back in response")
    void testCorrelationIdHeaderEchoed() throws Exception {
        String customCorrelationId = "test-corr-id-12345";

        mockMvc.perform(get("/api/v1/account")
                        .header("Authorization", "Bearer " + authResponse.accessToken())
                        .header(CorrelationIdFilter.CORRELATION_ID_HEADER, customCorrelationId))
                .andExpect(status().isOk())
                .andExpect(header().string(CorrelationIdFilter.CORRELATION_ID_HEADER, customCorrelationId));
    }

    @Test
    @DisplayName("Correlation ID: Missing X-Correlation-Id header automatically generates one in response")
    void testCorrelationIdHeaderAutoGenerated() throws Exception {
        MvcResult result = mockMvc.perform(get("/api/v1/account")
                        .header("Authorization", "Bearer " + authResponse.accessToken()))
                .andExpect(status().isOk())
                .andExpect(header().exists(CorrelationIdFilter.CORRELATION_ID_HEADER))
                .andReturn();

        String generatedId = result.getResponse().getHeader(CorrelationIdFilter.CORRELATION_ID_HEADER);
        assertThat(generatedId).isNotBlank();
    }
}
